# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: yzungula <yzungula@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/10/28 13:04:41 by yzungula          #+#    #+#              #
#    Updated: 2019/10/28 17:14:17 by yzungula         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine
MAINTAINER Yamkela Zungula (yzungula@student.wethinkcode.co.za)
# CMD ["ls", "-l", "bin"]
RUN apk update
RUN apk add vim
RUN vim testVim

# CMD ["apt-get", "update"]
# CMD ["apt-get", "install vim"]
