# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: yzungula <yzungula@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/10/28 13:04:41 by yzungula          #+#    #+#              #
#    Updated: 2019/10/29 16:40:00 by yzungula         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine
MAINTAINER Yamkela Zungula (yzungula@student.wethinkcode.co.za)

RUN apk update
RUN apk upgrade
RUN apk add vim

CMD ["vim"]

